set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speed_btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speed_btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speed_btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports clean_btn]
set_property IOSTANDARD LVCMOS33 [get_ports countdown]
set_property IOSTANDARD LVCMOS33 [get_ports menu_btn]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN K2 [get_ports {mode[0]}]
set_property PACKAGE_PIN J2 [get_ports {mode[1]}]
set_property PACKAGE_PIN J3 [get_ports {mode[2]}]
set_property PACKAGE_PIN R1 [get_ports {speed_btn[0]}]
set_property PACKAGE_PIN N4 [get_ports {speed_btn[1]}]
set_property PACKAGE_PIN M4 [get_ports {speed_btn[2]}]
set_property PACKAGE_PIN R2 [get_ports clean_btn]
set_property PACKAGE_PIN P15 [get_ports reset]
set_property PACKAGE_PIN R15 [get_ports menu_btn]
set_property PACKAGE_PIN F6 [get_ports countdown]



set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_select[0]}]
set_property PACKAGE_PIN B4 [get_ports {tub_control_1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control_1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control_1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control_1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control_1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control_1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control_1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control_1[0]}]
set_property PACKAGE_PIN D4 [get_ports {tub_control_2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control_2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control_2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control_2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control_2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control_2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control_2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control_2[0]}]
set_property PACKAGE_PIN G2 [get_ports {tub_select[7]}]
set_property PACKAGE_PIN C2 [get_ports {tub_select[6]}]
set_property PACKAGE_PIN C1 [get_ports {tub_select[5]}]
set_property PACKAGE_PIN H1 [get_ports {tub_select[4]}]
set_property PACKAGE_PIN G1 [get_ports {tub_select[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_select[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_select[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_select[0]}]
set_property PACKAGE_PIN P4 [get_ports display_mode]
set_property IOSTANDARD LVCMOS33 [get_ports display_mode]
set_property PACKAGE_PIN U4 [get_ports increase_key]
set_property IOSTANDARD LVCMOS33 [get_ports increase_key]
set_property PACKAGE_PIN P3 [get_ports set_mode]
set_property PACKAGE_PIN P2 [get_ports set_select]
set_property IOSTANDARD LVCMOS33 [get_ports set_mode]
set_property IOSTANDARD LVCMOS33 [get_ports set_select]



set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports speaker]


set_property IOSTANDARD LVCMOS33 [get_ports reminder]
set_property PACKAGE_PIN K3 [get_ports reminder]


set_property IOSTANDARD LVCMOS33 [get_ports pwm]
set_property PACKAGE_PIN T1 [get_ports pwm]
set_property PACKAGE_PIN H17 [get_ports speaker]
